version: '3'

services:
  uec-piano-hp:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "yarn dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - default
volumes:
  node_modules:
  